name: Update README

on:
  push: 
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: ${{ secrets.AOC_USER_ID }}
          leaderboardId: ${{ secrets.AOC_LEADERBOARD_ID }}
          sessionCookie: ${{ secrets.AOC_SESSION_COOKIE }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update README stars
